### ISSUE TITLE
Extension is reported as a conflicting keymap

### ISSUE THREAD

**Issue by TBBle** [HosseinAgha/vscode-open-react-component-style#1]
VS Code considers [any extension with 'Keymaps' in its category as a keymap extension](https://github.com/Microsoft/vscode/blob/e8b1ee0b4d016bc38bbc1cf06d6d1868760d5fe8/src/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#L137).

And it also [complains if more than one keymap extension is active](https://github.com/Microsoft/vscode/blob/e8b1ee0b4d016bc38bbc1cf06d6d1868760d5fe8/src/vs/workbench/parts/extensions/electron-browser/extensionsUtils.ts#L56).

It's trying to avoid conflicts between full-keyboard mappings, e.g., [Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim), [Sublime](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings), per @chrmarti on https://github.com/Microsoft/vscode/issues/24727#issuecomment-297867450

The simplest solution would be to remove the Keymaps category from this extension.

**Comment by HosseinAgha** [comment]
@TBBle thank you. I just published the package without keymaps category.
